version: "3.9"

services:
  chatbot-app:
    build: 
      context: .
      dockerfile: Dockerfile
      # target: production # development
    # image: chatbot-app:latest
    container_name: chatbot_app
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      VERIFY_TOKEN: ${VERIFY_TOKEN}
      FACEBOOK_PAGE_ACCESS_TOKEN: ${FACEBOOK_PAGE_ACCESS_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      USE_MODEL: openai
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app:cached
    #   - /app/node_modules
    # working_dir: /app
    # command: node server.js
  

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
